### ISSUE TITLE
Auto Captcha no longer working

### ISSUE THREAD

**Issue by AloW0304** [MehulKhanna/PokeGrinder#42] opened 2024-02-10 01:55 UTC
Unsure as to why the captcha solver isn't working anymore as it has been over the past few days. But now however whenever a captcha comes up I get this error message:
Downloading https://cdn.discordapp.com/attachments/970646862887530540/1205690833714810970/1491468769118.png to '1491468769118.png'...
⚠️ Download failure, retrying 1/3 https://cdn.discordapp.com/attachments/970646862887530540/1205690833714810970/1491468769118.png...
################################################################################################################################################################# 100.0%
2024-02-10 12:44:56 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 600, in _run_event
    await coro(*args, **kwargs)
  File "/Users/Destop/PokeGrinder-2.4 2/cogs/captcha.py", line 32, in on_message
    solve_captcha(message.embeds[0].image.url.split("?")[0])
  File "/Users/Desktop/PokeGrinder-2.4 2/modules/captcha_solver.py", line 8, in solve_captcha
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/engine/model.py", line 406, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 204, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 272, in stream_inference
    for batch in self.dataset:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/data/loaders.py", line 347, in __next__
    raise FileNotFoundError(f"Image Not Found {path}")
FileNotFoundError: Image Not Found /Users/Desktop/PokeGrinder-2.4 2/1491468769118.png

however the captcha file is always downloaded into the folder (PokeGrinder-2.4 2) so I'm unsure as to what has gone wrong.

**Comment by AloW0304** [comment] 2024-02-11 06:29
Any ideas? I've been trying to problem-solve over the past day, but nothing seems to make a difference.
![image](https://github.com/MehulKhanna/PokeGrinder/assets/109468340/a1c9a137-8e03-408d-9875-f326935e3972)
as seen in the image, image png's clog up the folder since they can't be detected to be solved or deleted.
I've since deleted and redownloaded V2.4 and tried on a different device with no success.

**Comment by MehulKhanna** [comment] 2024-02-11 06:32
> Any ideas? I've been trying to problem-solve over the past day, but nothing seems to make a difference. ![image](https://private-user-images.githubusercontent.com/109468340/303902122-a1c9a137-8e03-408d-9875-f326935e3972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzMzMTcsIm5iZiI6MTcwNzYzMzAxNywicGF0aCI6Ii8xMDk0NjgzNDAvMzAzOTAyMTIyLWExYzlhMTM3LThlMDMtNDA4ZC05ODc1LWYzMjY5MzVlMzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNjMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjYxOGJmMjc5N2Y5MDlkY2E3ZDdjMjQyZTZkZmRmMjUzMTZjZmUzNjNlMWYwNWM4MjJjZTFjYzU5M2IzNmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fAXxwaqkkkIMh9GMtg2D9wue0DrfDhziN2g6mbGVJzk) as seen in the image, image png's clog up the folder since they can't be detected to be solved or deleted. I've since deleted and redownloaded V2.4 and tried on a different device with no success.

In the past some users have had issues with python not being able to access other files. I don't have a mac so I cannot reproduce this. But I can make it store the image in memory instead of on disk in the next commit.

**Comment by MehulKhanna** [comment] 2024-02-17 14:10
> Any ideas? I've been trying to problem-solve over the past day, but nothing seems to make a difference. ![image](https://private-user-images.githubusercontent.com/109468340/303902122-a1c9a137-8e03-408d-9875-f326935e3972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzkyOTUsIm5iZiI6MTcwODE3ODk5NSwicGF0aCI6Ii8xMDk0NjgzNDAvMzAzOTAyMTIyLWExYzlhMTM3LThlMDMtNDA4ZC05ODc1LWYzMjY5MzVlMzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNDA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGYxOTk1ZWM5MTUyZDk4MWU0ODUxODFjNDFiYzg2YTU5YTg3ZjM4NDIxYzQ2YTU4N2M3ZGIwOWUxMzYyZGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Us2P3BbrPptKzVvI76Pwo3ByyHIdIlsMP47BSbo7n30) as seen in the image, image png's clog up the folder since they can't be detected to be solved or deleted. I've since deleted and redownloaded V2.4 and tried on a different device with no success.

I have found a possible fix for this. I will commit after more testing.

**Comment by MehulKhanna** [comment] 2024-02-17 17:32
Please try the latest release. This must be fixed now.

**Comment by AloW0304** [comment] 2024-02-18 00:38
working great so far, I'll keep running and let you know how it goes.

**Closed** 2024-02-18 16:59 UTC
Labels: Bug
